### ISSUE TITLE
Poor user experience mixing DSC requirements

### ISSUE THREAD

**Issue by plaisted** [microsoft/Requirements#19] opened 2019-07-08 19:27 UTC
Examples of using normal requirements mixed with DSC requirements would be helpful. The suggested method of using implicit and defining an array does not work if DSC requirements are inserted. Error below is given:
```
The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.
```

A current workaround is to pipe the requirements array to New-Requirement while splatting the hashtable. Because we need to splat we have to use a foreach-object instead of a normal pipe:
```
$requirements | % { $r = $_; New-Requirement @r } | Invoke-Requirement | Format-Callstack
```

**Comment by omiossec** [comment] 2019-07-08 19:40
Hi Could you please include the code to reproduce the issues

**Comment by plaisted** [comment] 2019-07-08 20:14
Sure, it's mixing any DSC requirement with a non-dsc requirement.
```
Import-Module Requirements

$requirements = @(
    @{
        Name     = "Resource 1"
        Describe = "Resource 1 is present in the system"
        Test     = { $true }
    },
    @{
        Name         = "TestName"
        Describe     = "Teset"
        ResourceName = "File"
        ModuleName   = "PSDesiredStateConfiguration"
        Property     = @{
            DestinationPath =  'c:\temp'
            Ensure = "Present"
            Type = "Directory"
        }
    }
)

$requirements | Invoke-Requirement | Format-Checklist
```

**Comment by omiossec** [comment] 2019-07-08 21:22
Thanks you
DSC requirements need to be converted to a requirement type, this is the purpose of the New-Requirement cmdlet. 
To using DSC and Requirement type in the same var implies a change in the requirement object type

**Comment by chriskuech** [comment] 2019-07-09 15:54
@omiossec is correct.  The only reason piping hashes to `Invoke-Requirement`s works is because they are [implicitly casted](https://medium.com/faun/functional-powershell-with-classes-820c8e9acd8f?source=friends_link&sk=9570a8944584ba79819dd755954b7534) to Requirement objects (they adhere to the `Test`/`Set` interface), whereas DSC resources do not adhere to this interface and must be converted with `New-Requirement`.  

I believe you can simplify your example a little:
```powershell
$requirements | % {New-Requirement @_} | Invoke-Requirement | Format-Callstack
```

**Comment by chriskuech** [comment] 2019-07-09 15:56
Closing the issue, but ideas for improved semantics are always appreciated

**Closed** 2019-07-09 15:55 UTC

**Comment by plaisted** [comment] 2019-07-09 22:26
@chriskuech
I understand why it doesn't work, my comment is just that currently the only prebuilt requirements are DSC based requirements and that if defining a list of hashtables is the suggested / easiest way to build requirements lists it would be nice to have DSC work natively with `Invoke-Requirement`.

`Invoke-Requirement` could automatically run `New-Requirement` on hashtables (why rely on implicit casting instead of explicitly running `New-Requirement`?) or the ability to pass a non-splatted hashtable to `New-Requirement` could be added so it can be done inline like:
```powershell
Import-Module Requirements

$requirements = @(
    @{
        Name     = "Resource 1"
        Describe = "Resource 1 is present in the system"
        Test     = { $true }
    },
    New-Requirement @{
        Name         = "TestName"
        Describe     = "Test"
        ResourceName = "File"
        ModuleName   = "PSDesiredStateConfiguration"
        Property     = @{
            DestinationPath =  'c:\temp'
            Ensure = "Present"
            Type = "Directory"
        }
    }
)

$requirements | Invoke-Requirement | Format-Checklist
```
or leave as hashtables and pipe without splatting:
```
$requirements | New-Requirement | Invoke-Requirement | Format-Checklist
```
but then again, if there's never a downside (maybe there is?) to running `New-Requirement` against the hashtables why wouldn't it just be included in Invoke-Requirement?

**Comment by chriskuech** [comment] 2019-07-10 00:06
The original implementation of `Invoke-Requirement` had the behavior you described, but we found that in more complex scenarios it was advantageous to declare your Requirements without immediately invoking them, more like a Desired State Configurations.

Your example should work if you just don't use a hashtable for your DSC requirement:
```powershell
$requirements = @(

    @{
        Name     = "Resource 1"
        Describe = "Resource 1 is present in the system"
        Test     = { $true }
    },

    (New-Requirement `
        -Name          "TestName" `
        -Describe      "Test" `
        -ResourceName  "File" `
        -ModuleName    "PSDesiredStateConfiguration" `
        -Property      @{
            DestinationPath = 'c:\temp'
            Ensure          = "Present"
            Type            = "Directory"
        }
    )

)
```

This pattern can also be beneficial:
```powershell
$requirements = & {

    @{
        Name     = "Resource 1"
        Describe = "Resource 1 is present in the system"
        Test     = { $true }
    }

    $splat = @{
        Name         = "TestName"
        Describe     = "Test"
        ResourceName = "File"
        ModuleName   = "PSDesiredStateConfiguration"
        Property     = @{
            DestinationPath =  'c:\temp'
            Ensure = "Present"
            Type = "Directory"
        }
    }
    New-Requirement @splat

}
```

**Comment by plaisted** [comment] 2019-07-10 00:41
I think `$requirements | % {New-Requirement @_} | Invoke-Requirement` is probably the least disruptive way. Obviously not a big deal just felt odd having to do it to every requirement set I've put together.

**Comment by chriskuech** [comment] 2019-07-10 00:58
Ya just for perspective, this v2 declaration style is a big improvement from v1.  V1 only supported `Invoke-Requirement`, which required this verbose declaration style that PSScriptAnalyzer-based formatters did not understand how to indent.

```powershell
Invoke-Requirement `
    -Describe "..." `
    -Test {
    ...
} `
    -Set { 
    ...
}

```
